[project]
name = "deviceid-tracker"
version = "0.1.0"
description = "Track device_id and redirect to Wongnai"
requires-python = ">=3.8"

dependencies = [
    "flask",
    "python-dotenv",
    "pandas",
    "gspread",
    "oauth2client",
    "requests",
    "flask-cors",
    "schedule"
]
